echo "== set has no long mood flags:"
"$BIN" --debug-complete-at 'set --m' <"$TEST_NULL_DEVICE"
"$BIN" --debug-complete-at 'set --i' <"$TEST_NULL_DEVICE"
echo "== set -M value:"
"$BIN" --debug-complete-at 'set -M ' <"$TEST_NULL_DEVICE"
echo "== set -L value:"
"$BIN" --debug-complete-at 'set -L ' <"$TEST_NULL_DEVICE"
echo "== set -M= value:"
"$BIN" --debug-complete-at 'set -M=' <"$TEST_NULL_DEVICE"
echo "== set -M= prefix:"
"$BIN" --debug-complete-at 'set -M=b' <"$TEST_NULL_DEVICE"
echo "== kosh --mood value:"
"$BIN" --debug-complete-at 'kosh --mood ' <"$TEST_NULL_DEVICE"
echo "== kosh --mood= value:"
"$BIN" --debug-complete-at 'kosh --mood=' <"$TEST_NULL_DEVICE"
echo "== kosh -M value:"
"$BIN" --debug-complete-at 'kosh -M ' <"$TEST_NULL_DEVICE"
echo "== kosh --init-moods value:"
"$BIN" --debug-complete-at 'kosh --init-moods ' <"$TEST_NULL_DEVICE"
echo "== kosh -L= prefix:"
"$BIN" --debug-complete-at 'kosh -L=k' <"$TEST_NULL_DEVICE"
echo "== assimilate --link-mood value:"
"$BIN" --debug-complete-at 'assimilate --link-mood ' <"$TEST_NULL_DEVICE"
echo "== assimilate --link-mood= prefix:"
"$BIN" --debug-complete-at 'assimilate --link-mood=d' <"$TEST_NULL_DEVICE"
echo "== assignment prefix is untouched:"
result=$("$BIN" --debug-complete-at 'MOOD=' <"$TEST_NULL_DEVICE") || exit 1
printf '%s\n' "$result" | grep -qxF bash
[ "$?" -eq 1 ] || exit 1
printf '0\n'
