#!/bin/bash
# The cases of expansion_list_operators_matrix.bash that Kosh does not yet
# expand as bash does. The matrix skips these keys, and this fixture
# runs only them. Remove a key once its case agrees with bash.
pending_cases=(
  'one_empty|:-d|@|2|'
  'one_empty|:-d|@|13|'
  'one_empty|:-d|*|2|'
  'one_empty|:-d|*|13|'
  'one_empty|:+p|@|2|'
  'one_empty|:+p|@|13|'
  'one_empty|:+p|*|2|'
  'one_empty|:+p|*|13|'
  'two_empty|:-d|@|8|'
  'two_empty|-d|@|8|'
  'two_empty|#?|@|8|'
  'two_empty|##*|@|8|'
  'two_empty|#x|@|8|'
  'two_empty|%?|@|8|'
  'two_empty|%%?|@|8|'
  'two_empty|%e|@|8|'
  'two_empty|/a/A|@|8|'
  'two_empty|//a/A|@|8|'
  'two_empty|/#?/<|@|8|'
  'two_empty|/%?/>|@|8|'
  'two_empty|//[ab]/-|@|8|'
  'two_empty|/?/|@|8|'
  'two_empty|^|@|8|'
  'two_empty|^^|@|8|'
  'two_empty|,|@|8|'
  'two_empty|,,|@|8|'
  'two_empty|~|@|8|'
  'two_empty|~~|@|8|'
  'two_empty|^^[ab]|@|8|'
  'two_empty|: -9|@|1|'
  'two_empty|: -9|@|2|'
  'two_empty|: -9|@|3|'
  'two_empty|: -9|@|5|'
  'two_empty|: -9|@|8|'
  'two_empty|: -9|@|10|'
  'two_empty|: -9|@|11|'
  'two_empty|: -9|@|12|'
  'two_empty|: -9|@|13|'
  'two_empty|: -9|@|14|'
  'two_empty|: -9|*|1|'
  'two_empty|: -9|*|2|'
  'two_empty|: -9|*|3|'
  'two_empty|: -9|*|5|'
  'two_empty|: -9|*|8|'
  'two_empty|: -9|*|10|'
  'two_empty|: -9|*|11|'
  'two_empty|: -9|*|12|'
  'two_empty|: -9|*|13|'
  'two_empty|: -9|*|14|'
  'sparse||@|2|'
  'sparse||@|3|'
  'sparse||@|10|'
  'sparse||@|11|'
  'sparse||@|12|'
  'sparse||@|13|'
  'sparse||@|14|'
  'sparse||*|2|'
  'sparse||*|3|'
  'sparse||*|7|'
  'sparse||*|8|'
  'sparse||*|10|'
  'sparse||*|11|'
  'sparse||*|12|'
  'sparse||*|13|'
  'sparse||*|14|'
  'sparse|:-d|@|8|'
  'sparse|-d|@|8|'
  'sparse|#?|@|8|'
  'sparse|##*|@|8|'
  'sparse|#x|@|8|'
  'sparse|%?|@|8|'
  'sparse|%%?|@|8|'
  'sparse|%e|@|8|'
  'sparse|/a/A|@|8|'
  'sparse|//a/A|@|8|'
  'sparse|/#?/<|@|8|'
  'sparse|/%?/>|@|8|'
  'sparse|//[ab]/-|@|8|'
  'sparse|/?/|@|8|'
  'sparse|^|@|8|'
  'sparse|^^|@|8|'
  'sparse|,|@|8|'
  'sparse|,,|@|8|'
  'sparse|~|@|8|'
  'sparse|~~|@|8|'
  'sparse|^^[ab]|@|8|'
  'sparse|:1|@|0|'
  'sparse|:1|@|1|'
  'sparse|:1|@|2|'
  'sparse|:1|@|3|'
  'sparse|:1|@|4|'
  'sparse|:1|@|5|'
  'sparse|:1|@|6|'
  'sparse|:1|@|7|'
  'sparse|:1|@|8|'
  'sparse|:1|@|13|'
  'sparse|:1|@|14|'
  'sparse|:1|*|0|'
  'sparse|:1|*|1|'
  'sparse|:1|*|2|'
  'sparse|:1|*|3|'
  'sparse|:1|*|4|'
  'sparse|:1|*|5|'
  'sparse|:1|*|6|'
  'sparse|:1|*|7|'
  'sparse|:1|*|8|'
  'sparse|:1|*|13|'
  'sparse|:1|*|14|'
  'sparse|:1:1|@|0|'
  'sparse|:1:1|@|1|'
  'sparse|:1:1|@|2|'
  'sparse|:1:1|@|3|'
  'sparse|:1:1|@|4|'
  'sparse|:1:1|@|5|'
  'sparse|:1:1|@|6|'
  'sparse|:1:1|@|7|'
  'sparse|:1:1|@|8|'
  'sparse|:1:1|@|13|'
  'sparse|:1:1|@|14|'
  'sparse|:1:1|*|0|'
  'sparse|:1:1|*|1|'
  'sparse|:1:1|*|2|'
  'sparse|:1:1|*|3|'
  'sparse|:1:1|*|4|'
  'sparse|:1:1|*|5|'
  'sparse|:1:1|*|6|'
  'sparse|:1:1|*|7|'
  'sparse|:1:1|*|8|'
  'sparse|:1:1|*|13|'
  'sparse|:1:1|*|14|'
  'sparse|: -2:1|@|0|'
  'sparse|: -2:1|@|1|'
  'sparse|: -2:1|@|2|'
  'sparse|: -2:1|@|3|'
  'sparse|: -2:1|@|4|'
  'sparse|: -2:1|@|5|'
  'sparse|: -2:1|@|6|'
  'sparse|: -2:1|@|7|'
  'sparse|: -2:1|@|8|'
  'sparse|: -2:1|@|13|'
  'sparse|: -2:1|@|14|'
  'sparse|: -2:1|*|0|'
  'sparse|: -2:1|*|1|'
  'sparse|: -2:1|*|2|'
  'sparse|: -2:1|*|3|'
  'sparse|: -2:1|*|4|'
  'sparse|: -2:1|*|5|'
  'sparse|: -2:1|*|6|'
  'sparse|: -2:1|*|7|'
  'sparse|: -2:1|*|8|'
  'sparse|: -2:1|*|13|'
  'sparse|: -2:1|*|14|'
  'sparse|: -9|@|0|'
  'sparse|: -9|@|1|'
  'sparse|: -9|@|2|'
  'sparse|: -9|@|3|'
  'sparse|: -9|@|4|'
  'sparse|: -9|@|5|'
  'sparse|: -9|@|6|'
  'sparse|: -9|@|7|'
  'sparse|: -9|@|8|'
  'sparse|: -9|@|10|'
  'sparse|: -9|@|11|'
  'sparse|: -9|@|12|'
  'sparse|: -9|@|13|'
  'sparse|: -9|@|14|'
  'sparse|: -9|*|0|'
  'sparse|: -9|*|1|'
  'sparse|: -9|*|2|'
  'sparse|: -9|*|3|'
  'sparse|: -9|*|4|'
  'sparse|: -9|*|5|'
  'sparse|: -9|*|6|'
  'sparse|: -9|*|7|'
  'sparse|: -9|*|8|'
  'sparse|: -9|*|10|'
  'sparse|: -9|*|11|'
  'sparse|: -9|*|12|'
  'sparse|: -9|*|13|'
  'sparse|: -9|*|14|'
  'spaces|:-d|@|8|'
  'spaces|-d|@|8|'
  'spaces|#?|@|8|'
  'spaces|##*|@|8|'
  'spaces|#x|@|8|'
  'spaces|%?|@|8|'
  'spaces|%%?|@|8|'
  'spaces|%e|@|8|'
  'spaces|/a/A|@|8|'
  'spaces|//a/A|@|8|'
  'spaces|/#?/<|@|8|'
  'spaces|/%?/>|@|8|'
  'spaces|//[ab]/-|@|8|'
  'spaces|/?/|@|8|'
  'spaces|^|@|8|'
  'spaces|^^|@|8|'
  'spaces|,|@|8|'
  'spaces|,,|@|8|'
  'spaces|~|@|8|'
  'spaces|~~|@|8|'
  'spaces|^^[ab]|@|8|'
  'spaces|: -9|@|0|'
  'spaces|: -9|@|1|'
  'spaces|: -9|@|2|'
  'spaces|: -9|@|3|'
  'spaces|: -9|@|4|'
  'spaces|: -9|@|5|'
  'spaces|: -9|@|6|'
  'spaces|: -9|@|7|'
  'spaces|: -9|@|8|'
  'spaces|: -9|@|10|'
  'spaces|: -9|@|11|'
  'spaces|: -9|@|12|'
  'spaces|: -9|@|13|'
  'spaces|: -9|@|14|'
  'spaces|: -9|*|0|'
  'spaces|: -9|*|1|'
  'spaces|: -9|*|2|'
  'spaces|: -9|*|3|'
  'spaces|: -9|*|4|'
  'spaces|: -9|*|5|'
  'spaces|: -9|*|6|'
  'spaces|: -9|*|7|'
  'spaces|: -9|*|8|'
  'spaces|: -9|*|10|'
  'spaces|: -9|*|11|'
  'spaces|: -9|*|12|'
  'spaces|: -9|*|13|'
  'spaces|: -9|*|14|'
  'glob|:-d|@|8|'
  'glob|-d|@|8|'
  'glob|#?|@|8|'
  'glob|##*|@|8|'
  'glob|#x|@|8|'
  'glob|%?|@|8|'
  'glob|%%?|@|8|'
  'glob|%e|@|8|'
  'glob|/a/A|@|8|'
  'glob|//a/A|@|8|'
  'glob|/#?/<|@|8|'
  'glob|/%?/>|@|8|'
  'glob|//[ab]/-|@|8|'
  'glob|/?/|@|8|'
  'glob|^|@|8|'
  'glob|^^|@|8|'
  'glob|,|@|8|'
  'glob|,,|@|8|'
  'glob|~|@|8|'
  'glob|~~|@|8|'
  'glob|^^[ab]|@|8|'
  'glob|: -9|@|0|'
  'glob|: -9|@|1|'
  'glob|: -9|@|2|'
  'glob|: -9|@|3|'
  'glob|: -9|@|4|'
  'glob|: -9|@|5|'
  'glob|: -9|@|6|'
  'glob|: -9|@|7|'
  'glob|: -9|@|8|'
  'glob|: -9|@|10|'
  'glob|: -9|@|11|'
  'glob|: -9|@|12|'
  'glob|: -9|@|13|'
  'glob|: -9|@|14|'
  'glob|: -9|*|0|'
  'glob|: -9|*|1|'
  'glob|: -9|*|2|'
  'glob|: -9|*|3|'
  'glob|: -9|*|4|'
  'glob|: -9|*|5|'
  'glob|: -9|*|6|'
  'glob|: -9|*|7|'
  'glob|: -9|*|8|'
  'glob|: -9|*|10|'
  'glob|: -9|*|11|'
  'glob|: -9|*|12|'
  'glob|: -9|*|13|'
  'glob|: -9|*|14|'
  'quotes|:-d|@|8|'
  'quotes|-d|@|8|'
  'quotes|#?|@|8|'
  'quotes|##*|@|8|'
  'quotes|#x|@|8|'
  'quotes|%?|@|8|'
  'quotes|%%?|@|8|'
  'quotes|%e|@|8|'
  'quotes|/a/A|@|8|'
  'quotes|//a/A|@|8|'
  'quotes|/#?/<|@|8|'
  'quotes|/%?/>|@|8|'
  'quotes|//[ab]/-|@|8|'
  'quotes|/?/|@|8|'
  'quotes|^|@|8|'
  'quotes|^^|@|8|'
  'quotes|,|@|8|'
  'quotes|,,|@|8|'
  'quotes|~|@|8|'
  'quotes|~~|@|8|'
  'quotes|^^[ab]|@|8|'
  'quotes|: -9|@|0|'
  'quotes|: -9|@|1|'
  'quotes|: -9|@|2|'
  'quotes|: -9|@|3|'
  'quotes|: -9|@|4|'
  'quotes|: -9|@|5|'
  'quotes|: -9|@|6|'
  'quotes|: -9|@|7|'
  'quotes|: -9|@|8|'
  'quotes|: -9|@|10|'
  'quotes|: -9|@|11|'
  'quotes|: -9|@|12|'
  'quotes|: -9|@|13|'
  'quotes|: -9|@|14|'
  'quotes|: -9|*|0|'
  'quotes|: -9|*|1|'
  'quotes|: -9|*|2|'
  'quotes|: -9|*|3|'
  'quotes|: -9|*|4|'
  'quotes|: -9|*|5|'
  'quotes|: -9|*|6|'
  'quotes|: -9|*|7|'
  'quotes|: -9|*|8|'
  'quotes|: -9|*|10|'
  'quotes|: -9|*|11|'
  'quotes|: -9|*|12|'
  'quotes|: -9|*|13|'
  'quotes|: -9|*|14|'
  'newline|:-d|@|8|'
  'newline|-d|@|8|'
  'newline|#?|@|8|'
  'newline|##*|@|8|'
  'newline|#x|@|8|'
  'newline|%?|@|8|'
  'newline|%%?|@|8|'
  'newline|%e|@|8|'
  'newline|/a/A|@|8|'
  'newline|//a/A|@|8|'
  'newline|/#?/<|@|8|'
  'newline|/%?/>|@|8|'
  'newline|//[ab]/-|@|8|'
  'newline|/?/|@|8|'
  'newline|^|@|8|'
  'newline|^^|@|8|'
  'newline|,|@|8|'
  'newline|,,|@|8|'
  'newline|~|@|8|'
  'newline|~~|@|8|'
  'newline|^^[ab]|@|8|'
  'newline|: -9|@|0|'
  'newline|: -9|@|1|'
  'newline|: -9|@|2|'
  'newline|: -9|@|3|'
  'newline|: -9|@|4|'
  'newline|: -9|@|5|'
  'newline|: -9|@|6|'
  'newline|: -9|@|7|'
  'newline|: -9|@|8|'
  'newline|: -9|@|10|'
  'newline|: -9|@|11|'
  'newline|: -9|@|12|'
  'newline|: -9|@|13|'
  'newline|: -9|@|14|'
  'newline|: -9|*|0|'
  'newline|: -9|*|1|'
  'newline|: -9|*|2|'
  'newline|: -9|*|3|'
  'newline|: -9|*|4|'
  'newline|: -9|*|5|'
  'newline|: -9|*|6|'
  'newline|: -9|*|7|'
  'newline|: -9|*|8|'
  'newline|: -9|*|10|'
  'newline|: -9|*|11|'
  'newline|: -9|*|12|'
  'newline|: -9|*|13|'
  'newline|: -9|*|14|'
  'control|:-d|@|8|'
  'control|-d|@|8|'
  'control|#?|@|8|'
  'control|##*|@|8|'
  'control|#x|@|8|'
  'control|%?|@|8|'
  'control|%%?|@|8|'
  'control|%e|@|8|'
  'control|/a/A|@|8|'
  'control|//a/A|@|8|'
  'control|/#?/<|@|8|'
  'control|/%?/>|@|8|'
  'control|//[ab]/-|@|8|'
  'control|/?/|@|8|'
  'control|^|@|8|'
  'control|^^|@|8|'
  'control|,|@|8|'
  'control|,,|@|8|'
  'control|~|@|8|'
  'control|~~|@|8|'
  'control|^^[ab]|@|8|'
  'control|: -9|@|0|'
  'control|: -9|@|1|'
  'control|: -9|@|2|'
  'control|: -9|@|3|'
  'control|: -9|@|4|'
  'control|: -9|@|5|'
  'control|: -9|@|6|'
  'control|: -9|@|7|'
  'control|: -9|@|8|'
  'control|: -9|@|10|'
  'control|: -9|@|11|'
  'control|: -9|@|12|'
  'control|: -9|@|13|'
  'control|: -9|@|14|'
  'control|: -9|*|0|'
  'control|: -9|*|1|'
  'control|: -9|*|2|'
  'control|: -9|*|3|'
  'control|: -9|*|4|'
  'control|: -9|*|5|'
  'control|: -9|*|6|'
  'control|: -9|*|7|'
  'control|: -9|*|8|'
  'control|: -9|*|10|'
  'control|: -9|*|11|'
  'control|: -9|*|12|'
  'control|: -9|*|13|'
  'control|: -9|*|14|'
  'two_empty|:-d|@|8|ifs_unset'
  'two_empty|/a/A|@|8|ifs_unset'
  'two_empty|^^|@|8|ifs_unset'
  'two_empty|#?|@|8|ifs_unset'
  'spaces|:-d|@|8|ifs_unset'
  'spaces|/a/A|@|8|ifs_unset'
  'spaces|^^|@|8|ifs_unset'
  'spaces|#?|@|8|ifs_unset'
  'glob|:-d|@|8|ifs_unset'
  'glob|/a/A|@|8|ifs_unset'
  'glob|^^|@|8|ifs_unset'
  'glob|#?|@|8|ifs_unset'
  'newline|:-d|@|8|ifs_unset'
  'newline|/a/A|@|8|ifs_unset'
  'newline|^^|@|8|ifs_unset'
  'newline|#?|@|8|ifs_unset'
  'two_empty|:-d|@|7|ifs_empty'
  'two_empty|:-d|@|8|ifs_empty'
  'two_empty|:-d|*|0|ifs_empty'
  'two_empty|:-d|*|2|ifs_empty'
  'two_empty|:-d|*|4|ifs_empty'
  'two_empty|:-d|*|6|ifs_empty'
  'two_empty|:-d|*|7|ifs_empty'
  'two_empty|:-d|*|9|ifs_empty'
  'two_empty|:-d|*|10|ifs_empty'
  'two_empty|:-d|*|11|ifs_empty'
  'two_empty|:-d|*|13|ifs_empty'
  'two_empty|/a/A|@|7|ifs_empty'
  'two_empty|/a/A|@|8|ifs_empty'
  'two_empty|^^|@|7|ifs_empty'
  'two_empty|^^|@|8|ifs_empty'
  'two_empty|#?|@|0|ifs_empty'
  'two_empty|#?|@|4|ifs_empty'
  'two_empty|#?|@|6|ifs_empty'
  'two_empty|#?|@|8|ifs_empty'
  'two_empty|#?|*|0|ifs_empty'
  'two_empty|#?|*|4|ifs_empty'
  'two_empty|#?|*|6|ifs_empty'
  'two_empty|#?|*|7|ifs_empty'
  'spaces||*|7|ifs_empty'
  'spaces|:-d|@|7|ifs_empty'
  'spaces|:-d|@|8|ifs_empty'
  'spaces|:-d|*|7|ifs_empty'
  'spaces|/a/A|@|7|ifs_empty'
  'spaces|/a/A|@|8|ifs_empty'
  'spaces|/a/A|*|7|ifs_empty'
  'spaces|^^|@|7|ifs_empty'
  'spaces|^^|@|8|ifs_empty'
  'spaces|^^|*|7|ifs_empty'
  'spaces|#?|@|0|ifs_empty'
  'spaces|#?|@|2|ifs_empty'
  'spaces|#?|@|4|ifs_empty'
  'spaces|#?|@|6|ifs_empty'
  'spaces|#?|@|7|ifs_empty'
  'spaces|#?|@|8|ifs_empty'
  'spaces|#?|@|9|ifs_empty'
  'spaces|#?|@|13|ifs_empty'
  'spaces|#?|*|0|ifs_empty'
  'spaces|#?|*|4|ifs_empty'
  'spaces|#?|*|6|ifs_empty'
  'spaces|#?|*|7|ifs_empty'
  'glob||*|7|ifs_empty'
  'glob|:-d|@|7|ifs_empty'
  'glob|:-d|@|8|ifs_empty'
  'glob|:-d|*|7|ifs_empty'
  'glob|/a/A|@|7|ifs_empty'
  'glob|/a/A|@|8|ifs_empty'
  'glob|/a/A|*|7|ifs_empty'
  'glob|^^|@|7|ifs_empty'
  'glob|^^|@|8|ifs_empty'
  'glob|^^|*|7|ifs_empty'
  'glob|#?|@|0|ifs_empty'
  'glob|#?|@|4|ifs_empty'
  'glob|#?|@|6|ifs_empty'
  'glob|#?|@|8|ifs_empty'
  'glob|#?|*|0|ifs_empty'
  'glob|#?|*|4|ifs_empty'
  'glob|#?|*|6|ifs_empty'
  'glob|#?|*|7|ifs_empty'
  'newline||*|7|ifs_empty'
  'newline|:-d|@|7|ifs_empty'
  'newline|:-d|@|8|ifs_empty'
  'newline|:-d|*|7|ifs_empty'
  'newline|/a/A|@|7|ifs_empty'
  'newline|/a/A|@|8|ifs_empty'
  'newline|/a/A|*|7|ifs_empty'
  'newline|^^|@|7|ifs_empty'
  'newline|^^|@|8|ifs_empty'
  'newline|^^|*|7|ifs_empty'
  'newline|#?|@|0|ifs_empty'
  'newline|#?|@|4|ifs_empty'
  'newline|#?|@|6|ifs_empty'
  'newline|#?|@|8|ifs_empty'
  'newline|#?|*|0|ifs_empty'
  'newline|#?|*|4|ifs_empty'
  'newline|#?|*|6|ifs_empty'
  'newline|#?|*|7|ifs_empty'
  'two_empty||@|6|ifs_colon'
  'two_empty||@|7|ifs_colon'
  'two_empty||*|6|ifs_colon'
  'two_empty|:-d|@|6|ifs_colon'
  'two_empty|:-d|@|8|ifs_colon'
  'two_empty|:-d|*|6|ifs_colon'
  'two_empty|/a/A|@|3|ifs_colon'
  'two_empty|/a/A|@|6|ifs_colon'
  'two_empty|/a/A|@|7|ifs_colon'
  'two_empty|/a/A|@|8|ifs_colon'
  'two_empty|/a/A|@|9|ifs_colon'
  'two_empty|/a/A|@|10|ifs_colon'
  'two_empty|/a/A|@|11|ifs_colon'
  'two_empty|/a/A|@|14|ifs_colon'
  'two_empty|/a/A|*|6|ifs_colon'
  'two_empty|^^|@|3|ifs_colon'
  'two_empty|^^|@|6|ifs_colon'
  'two_empty|^^|@|7|ifs_colon'
  'two_empty|^^|@|8|ifs_colon'
  'two_empty|^^|@|9|ifs_colon'
  'two_empty|^^|@|10|ifs_colon'
  'two_empty|^^|@|11|ifs_colon'
  'two_empty|^^|@|14|ifs_colon'
  'two_empty|^^|*|6|ifs_colon'
  'two_empty|#?|@|2|ifs_colon'
  'two_empty|#?|@|3|ifs_colon'
  'two_empty|#?|@|6|ifs_colon'
  'two_empty|#?|@|7|ifs_colon'
  'two_empty|#?|@|8|ifs_colon'
  'two_empty|#?|@|9|ifs_colon'
  'two_empty|#?|@|10|ifs_colon'
  'two_empty|#?|@|11|ifs_colon'
  'two_empty|#?|@|13|ifs_colon'
  'two_empty|#?|@|14|ifs_colon'
  'two_empty|#?|*|6|ifs_colon'
  'spaces||@|7|ifs_colon'
  'spaces|:-d|@|8|ifs_colon'
  'spaces|/a/A|@|3|ifs_colon'
  'spaces|/a/A|@|8|ifs_colon'
  'spaces|/a/A|@|14|ifs_colon'
  'spaces|^^|@|3|ifs_colon'
  'spaces|^^|@|8|ifs_colon'
  'spaces|^^|@|14|ifs_colon'
  'spaces|:1|@|3|ifs_colon'
  'spaces|:1|@|7|ifs_colon'
  'spaces|:1|@|14|ifs_colon'
  'spaces|#?|@|2|ifs_colon'
  'spaces|#?|@|3|ifs_colon'
  'spaces|#?|@|7|ifs_colon'
  'spaces|#?|@|8|ifs_colon'
  'spaces|#?|@|9|ifs_colon'
  'spaces|#?|@|13|ifs_colon'
  'spaces|#?|@|14|ifs_colon'
  'glob||@|7|ifs_colon'
  'glob|:-d|@|8|ifs_colon'
  'glob|/a/A|@|3|ifs_colon'
  'glob|/a/A|@|8|ifs_colon'
  'glob|/a/A|@|14|ifs_colon'
  'glob|^^|@|3|ifs_colon'
  'glob|^^|@|8|ifs_colon'
  'glob|^^|@|14|ifs_colon'
  'glob|:1|@|3|ifs_colon'
  'glob|:1|@|7|ifs_colon'
  'glob|:1|@|14|ifs_colon'
  'glob|#?|@|0|ifs_colon'
  'glob|#?|@|2|ifs_colon'
  'glob|#?|@|3|ifs_colon'
  'glob|#?|@|4|ifs_colon'
  'glob|#?|@|6|ifs_colon'
  'glob|#?|@|8|ifs_colon'
  'glob|#?|@|13|ifs_colon'
  'glob|#?|@|14|ifs_colon'
  'glob|#?|*|0|ifs_colon'
  'glob|#?|*|4|ifs_colon'
  'glob|#?|*|6|ifs_colon'
  'newline||@|7|ifs_colon'
  'newline|:-d|@|8|ifs_colon'
  'newline|/a/A|@|3|ifs_colon'
  'newline|/a/A|@|8|ifs_colon'
  'newline|/a/A|@|14|ifs_colon'
  'newline|^^|@|3|ifs_colon'
  'newline|^^|@|8|ifs_colon'
  'newline|^^|@|14|ifs_colon'
  'newline|:1|@|3|ifs_colon'
  'newline|:1|@|7|ifs_colon'
  'newline|:1|@|14|ifs_colon'
  'newline|#?|@|0|ifs_colon'
  'newline|#?|@|2|ifs_colon'
  'newline|#?|@|3|ifs_colon'
  'newline|#?|@|4|ifs_colon'
  'newline|#?|@|6|ifs_colon'
  'newline|#?|@|7|ifs_colon'
  'newline|#?|@|8|ifs_colon'
  'newline|#?|@|9|ifs_colon'
  'newline|#?|@|13|ifs_colon'
  'newline|#?|@|14|ifs_colon'
  'newline|#?|*|0|ifs_colon'
  'newline|#?|*|4|ifs_colon'
  'newline|#?|*|6|ifs_colon'
  'two_empty|:-d|@|8|ifs_space_colon'
  'two_empty|/a/A|@|8|ifs_space_colon'
  'two_empty|^^|@|8|ifs_space_colon'
  'two_empty|#?|@|8|ifs_space_colon'
  'spaces|:-d|@|8|ifs_space_colon'
  'spaces|/a/A|@|8|ifs_space_colon'
  'spaces|^^|@|8|ifs_space_colon'
  'spaces|#?|@|8|ifs_space_colon'
  'glob|:-d|@|8|ifs_space_colon'
  'glob|/a/A|@|8|ifs_space_colon'
  'glob|^^|@|8|ifs_space_colon'
  'glob|#?|@|8|ifs_space_colon'
  'newline|:-d|@|8|ifs_space_colon'
  'newline|/a/A|@|8|ifs_space_colon'
  'newline|^^|@|8|ifs_space_colon'
  'newline|#?|@|8|ifs_space_colon'
  'one_empty|:-d|@|2|nounset'
  'one_empty|:-d|@|13|nounset'
  'one_empty|:-d|*|2|nounset'
  'one_empty|:-d|*|13|nounset'
  'one_empty|:+p|@|2|nounset'
  'one_empty|:+p|@|13|nounset'
  'one_empty|:+p|*|2|nounset'
  'one_empty|:+p|*|13|nounset'
  'sparse||@|2|nounset'
  'sparse||@|13|nounset'
  'sparse||*|2|nounset'
  'sparse||*|13|nounset'
  'sparse|:1|@|0|nounset'
  'sparse|:1|@|1|nounset'
  'sparse|:1|@|2|nounset'
  'sparse|:1|@|6|nounset'
  'sparse|:1|@|13|nounset'
  'sparse|:1|*|0|nounset'
  'sparse|:1|*|1|nounset'
  'sparse|:1|*|2|nounset'
  'sparse|:1|*|6|nounset'
  'sparse|:1|*|13|nounset'
)
[ -n "${list_only-}" ] && return 0
is_pending_run=1
. "${BASH_SOURCE%/*}/expansion_list_operators_matrix.bash"
