#!/bin/bash
# The cases of nameref_contexts_matrix.bash that Kosh does not yet
# expand as bash does. The matrix skips these keys, and this fixture
# runs only them. Remove a key once its case agrees with bash.
pending_cases=(
  'element|${!ref[@]}||2|read'
  'element|${!ref[@]}||5|read'
  'element|${!ref[@]}||6|read'
  'element|${!ref[@]}||7|read'
  'scalar|ref+=(z)||0|write'
  'scalar|ref+=(z)||1|write'
  'scalar|ref+=(z)||2|write'
  'scalar|ref+=(z)||3|write'
  'scalar|unset "ref[1]"||0|write'
  'scalar|unset "ref[1]"||1|write'
  'scalar|unset "ref[1]"||2|write'
  'scalar|unset "ref[1]"||3|write'
  'empty_target|ref+=(z)||0|write'
  'empty_target|ref+=(z)||1|write'
  'empty_target|ref+=(z)||2|write'
  'empty_target|ref+=(z)||3|write'
  'empty_target|unset "ref[1]"||0|write'
  'empty_target|unset "ref[1]"||1|write'
  'empty_target|unset "ref[1]"||2|write'
  'empty_target|unset "ref[1]"||3|write'
  'element|ref=(x y)||0|write'
  'element|ref=(x y)||1|write'
  'element|ref=(x y)||2|write'
  'element|ref=(x y)||3|write'
  'element|ref+=(z)||0|write'
  'element|ref+=(z)||1|write'
  'element|ref+=(z)||2|write'
  'element|ref+=(z)||3|write'
  'element|ref[1]=elem||0|write'
  'element|ref[1]=elem||1|write'
  'element|ref[1]=elem||2|write'
  'element|ref[1]=elem||3|write'
  'element|ref[2]=k||0|write'
  'element|ref[2]=k||1|write'
  'element|ref[2]=k||2|write'
  'element|ref[2]=k||3|write'
  'element|read -ra ref <<< "r1 r2"||0|write'
  'element|read -ra ref <<< "r1 r2"||1|write'
  'element|read -ra ref <<< "r1 r2"||2|write'
  'element|read -ra ref <<< "r1 r2"||3|write'
  'element|mapfile -t ref <<< $'\''m1\nm2'\''||0|write'
  'element|mapfile -t ref <<< $'\''m1\nm2'\''||1|write'
  'element|mapfile -t ref <<< $'\''m1\nm2'\''||3|write'
  'element|export ref=exported||0|write'
  'element|export ref=exported||1|write'
  'element|export ref=exported||2|write'
  'element|export ref=exported||3|write'
  'element|f() { local -n lr=target; lr=via_name; }; f||0|write'
  'element|f() { local -n lr=target; lr=via_name; }; f||1|write'
  'element|f() { local -n lr=target; lr=via_name; }; f||2|write'
  'element|f() { local -n lr=target; lr=via_name; }; f||3|write'
  'array|ref=new||0|write'
  'array|ref=new||1|write'
  'array|ref=new||2|write'
  'array|ref=new||3|write'
  'array|ref+=more||0|write'
  'array|ref+=more||1|write'
  'array|ref+=more||2|write'
  'array|ref+=more||3|write'
  'array|((ref = 4 * 2))||0|write'
  'array|((ref = 4 * 2))||1|write'
  'array|((ref = 4 * 2))||2|write'
  'array|((ref = 4 * 2))||3|write'
  'array|((ref++))||0|write'
  'array|((ref++))||1|write'
  'array|((ref++))||2|write'
  'array|((ref++))||3|write'
  'array|let ref+=3||0|write'
  'array|let ref+=3||1|write'
  'array|let ref+=3||2|write'
  'array|let ref+=3||3|write'
  'array|read -r ref <<< rd||0|write'
  'array|read -r ref <<< rd||1|write'
  'array|read -r ref <<< rd||2|write'
  'array|read -r ref <<< rd||3|write'
  'array|printf -v ref %s pv||0|write'
  'array|printf -v ref %s pv||1|write'
  'array|printf -v ref %s pv||2|write'
  'array|printf -v ref %s pv||3|write'
  'array|export ref=exported||0|write'
  'array|export ref=exported||1|write'
  'array|export ref=exported||2|write'
  'array|export ref=exported||3|write'
  'array|OPTIND=1; getopts ab ref -b||0|write'
  'array|OPTIND=1; getopts ab ref -b||1|write'
  'array|OPTIND=1; getopts ab ref -b||2|write'
  'array|OPTIND=1; getopts ab ref -b||3|write'
  'array|f() { local -n lr=ref; lr=via_local; }; f||0|write'
  'array|f() { local -n lr=ref; lr=via_local; }; f||1|write'
  'array|f() { local -n lr=ref; lr=via_local; }; f||2|write'
  'array|f() { local -n lr=ref; lr=via_local; }; f||3|write'
  'array|f() { local -n lr=target; lr=via_name; }; f||0|write'
  'array|f() { local -n lr=target; lr=via_name; }; f||1|write'
  'array|f() { local -n lr=target; lr=via_name; }; f||2|write'
  'array|f() { local -n lr=target; lr=via_name; }; f||3|write'
  'assoc|ref=new||0|write'
  'assoc|ref=new||1|write'
  'assoc|ref=new||2|write'
  'assoc|ref=new||3|write'
  'assoc|ref+=more||0|write'
  'assoc|ref+=more||1|write'
  'assoc|ref+=more||2|write'
  'assoc|ref+=more||3|write'
  'assoc|ref[1]=elem||0|write'
  'assoc|ref[1]=elem||1|write'
  'assoc|ref[1]=elem||2|write'
  'assoc|ref[1]=elem||3|write'
  'assoc|((ref = 4 * 2))||0|write'
  'assoc|((ref = 4 * 2))||1|write'
  'assoc|((ref = 4 * 2))||2|write'
  'assoc|((ref = 4 * 2))||3|write'
  'assoc|((ref++))||0|write'
  'assoc|((ref++))||1|write'
  'assoc|((ref++))||2|write'
  'assoc|((ref++))||3|write'
  'assoc|let ref+=3||0|write'
  'assoc|let ref+=3||1|write'
  'assoc|let ref+=3||2|write'
  'assoc|let ref+=3||3|write'
  'assoc|read -r ref <<< rd||0|write'
  'assoc|read -r ref <<< rd||1|write'
  'assoc|read -r ref <<< rd||2|write'
  'assoc|read -r ref <<< rd||3|write'
  'assoc|read -ra ref <<< "r1 r2"||0|write'
  'assoc|read -ra ref <<< "r1 r2"||1|write'
  'assoc|read -ra ref <<< "r1 r2"||2|write'
  'assoc|read -ra ref <<< "r1 r2"||3|write'
  'assoc|printf -v ref %s pv||0|write'
  'assoc|printf -v ref %s pv||1|write'
  'assoc|printf -v ref %s pv||2|write'
  'assoc|printf -v ref %s pv||3|write'
  'assoc|mapfile -t ref <<< $'\''m1\nm2'\''||0|write'
  'assoc|mapfile -t ref <<< $'\''m1\nm2'\''||1|write'
  'assoc|mapfile -t ref <<< $'\''m1\nm2'\''||3|write'
  'assoc|: ${ref:=assigned}||0|write'
  'assoc|: ${ref:=assigned}||1|write'
  'assoc|: ${ref:=assigned}||2|write'
  'assoc|: ${ref:=assigned}||3|write'
  'assoc|export ref=exported||0|write'
  'assoc|export ref=exported||1|write'
  'assoc|export ref=exported||2|write'
  'assoc|export ref=exported||3|write'
  'assoc|OPTIND=1; getopts ab ref -b||0|write'
  'assoc|OPTIND=1; getopts ab ref -b||1|write'
  'assoc|OPTIND=1; getopts ab ref -b||2|write'
  'assoc|OPTIND=1; getopts ab ref -b||3|write'
  'assoc|f() { local -n lr=ref; lr=via_local; }; f||0|write'
  'assoc|f() { local -n lr=ref; lr=via_local; }; f||1|write'
  'assoc|f() { local -n lr=ref; lr=via_local; }; f||2|write'
  'assoc|f() { local -n lr=ref; lr=via_local; }; f||3|write'
  'assoc|f() { local -n lr=target; lr=via_name; }; f||0|write'
  'assoc|f() { local -n lr=target; lr=via_name; }; f||1|write'
  'assoc|f() { local -n lr=target; lr=via_name; }; f||2|write'
  'assoc|f() { local -n lr=target; lr=via_name; }; f||3|write'
  'chain|ref+=(z)||0|write'
  'chain|ref+=(z)||1|write'
  'chain|ref+=(z)||2|write'
  'chain|ref+=(z)||3|write'
  'chain|unset "ref[1]"||0|write'
  'chain|unset "ref[1]"||1|write'
  'chain|unset "ref[1]"||2|write'
  'chain|unset "ref[1]"||3|write'
  'integer|ref+=(z)||0|write'
  'integer|ref+=(z)||1|write'
  'integer|ref+=(z)||2|write'
  'integer|ref+=(z)||3|write'
  'integer|read -ra ref <<< "r1 r2"||0|write'
  'integer|read -ra ref <<< "r1 r2"||1|write'
  'integer|read -ra ref <<< "r1 r2"||2|write'
  'integer|read -ra ref <<< "r1 r2"||3|write'
  'integer|mapfile -t ref <<< $'\''m1\nm2'\''||0|write'
  'integer|mapfile -t ref <<< $'\''m1\nm2'\''||1|write'
  'integer|mapfile -t ref <<< $'\''m1\nm2'\''||3|write'
  'integer|unset "ref[1]"||0|write'
  'integer|unset "ref[1]"||1|write'
  'integer|unset "ref[1]"||2|write'
  'integer|unset "ref[1]"||3|write'
)
[ -n "${list_only-}" ] && return 0
is_pending_run=1
. "${BASH_SOURCE%/*}/nameref_contexts_matrix.bash"
