#!/bin/bash
# The cases of nameref_contexts_matrix.bash that Kosh does not yet
# expand as bash does. The matrix skips these keys, and this fixture
# runs only them. Remove a key once its case agrees with bash.
pending_cases=(
  'scalar|${ref[key]}||0|read'
  'scalar|${ref[key]}||1|read'
  'scalar|${ref[key]}||2|read'
  'scalar|${ref[key]}||3|read'
  'scalar|${ref[key]}||4|read'
  'scalar|${ref[key]}||5|read'
  'scalar|${ref[key]}||6|read'
  'scalar|${ref[key]}||7|read'
  'scalar|${ref[key]}||8|read'
  'scalar|${ref[key]}||9|read'
  'scalar|${ref[key]}||10|read'
  'unset_target|$ref||0|read'
  'unset_target|$ref||1|read'
  'unset_target|$ref||2|read'
  'unset_target|$ref||3|read'
  'unset_target|$ref||4|read'
  'unset_target|$ref||5|read'
  'unset_target|$ref||6|read'
  'unset_target|$ref||7|read'
  'unset_target|$ref||8|read'
  'unset_target|$ref||9|read'
  'unset_target|$ref||10|read'
  'unset_target|${ref}||0|read'
  'unset_target|${ref}||1|read'
  'unset_target|${ref}||2|read'
  'unset_target|${ref}||3|read'
  'unset_target|${ref}||4|read'
  'unset_target|${ref}||5|read'
  'unset_target|${ref}||6|read'
  'unset_target|${ref}||7|read'
  'unset_target|${ref}||8|read'
  'unset_target|${ref}||9|read'
  'unset_target|${ref}||10|read'
  'unset_target|${ref[key]}||0|read'
  'unset_target|${ref[key]}||1|read'
  'unset_target|${ref[key]}||2|read'
  'unset_target|${ref[key]}||3|read'
  'unset_target|${ref[key]}||4|read'
  'unset_target|${ref[key]}||5|read'
  'unset_target|${ref[key]}||6|read'
  'unset_target|${ref[key]}||7|read'
  'unset_target|${ref[key]}||8|read'
  'unset_target|${ref[key]}||9|read'
  'unset_target|${ref[key]}||10|read'
  'unset_target|${#ref}||0|read'
  'unset_target|${#ref}||1|read'
  'unset_target|${#ref}||2|read'
  'unset_target|${#ref}||3|read'
  'unset_target|${#ref}||4|read'
  'unset_target|${#ref}||5|read'
  'unset_target|${#ref}||6|read'
  'unset_target|${#ref}||7|read'
  'unset_target|${#ref}||8|read'
  'unset_target|${#ref}||9|read'
  'unset_target|${#ref}||10|read'
  'unset_target|$((ref + 1))||0|read'
  'unset_target|$((ref + 1))||1|read'
  'unset_target|$((ref + 1))||2|read'
  'unset_target|$((ref + 1))||3|read'
  'unset_target|$((ref + 1))||4|read'
  'unset_target|$((ref + 1))||5|read'
  'unset_target|$((ref + 1))||6|read'
  'unset_target|$((ref + 1))||7|read'
  'unset_target|$((ref + 1))||8|read'
  'unset_target|$((ref + 1))||9|read'
  'unset_target|$((ref + 1))||10|read'
  'empty_target|${ref[key]}||0|read'
  'empty_target|${ref[key]}||1|read'
  'empty_target|${ref[key]}||2|read'
  'empty_target|${ref[key]}||3|read'
  'empty_target|${ref[key]}||4|read'
  'empty_target|${ref[key]}||5|read'
  'empty_target|${ref[key]}||6|read'
  'empty_target|${ref[key]}||7|read'
  'empty_target|${ref[key]}||8|read'
  'empty_target|${ref[key]}||9|read'
  'empty_target|${ref[key]}||10|read'
  'element|${ref[@]}||0|read'
  'element|${ref[@]}||1|read'
  'element|${ref[@]}||2|read'
  'element|${ref[@]}||3|read'
  'element|${ref[@]}||4|read'
  'element|${ref[@]}||5|read'
  'element|${ref[@]}||6|read'
  'element|${ref[@]}||7|read'
  'element|${ref[@]}||8|read'
  'element|${ref[@]}||9|read'
  'element|${ref[@]}||10|read'
  'element|${ref[*]}||0|read'
  'element|${ref[*]}||1|read'
  'element|${ref[*]}||2|read'
  'element|${ref[*]}||3|read'
  'element|${ref[*]}||4|read'
  'element|${ref[*]}||5|read'
  'element|${ref[*]}||6|read'
  'element|${ref[*]}||7|read'
  'element|${ref[*]}||8|read'
  'element|${ref[*]}||9|read'
  'element|${ref[*]}||10|read'
  'element|${ref[0]}||0|read'
  'element|${ref[0]}||1|read'
  'element|${ref[0]}||2|read'
  'element|${ref[0]}||3|read'
  'element|${ref[0]}||4|read'
  'element|${ref[0]}||5|read'
  'element|${ref[0]}||6|read'
  'element|${ref[0]}||7|read'
  'element|${ref[0]}||8|read'
  'element|${ref[0]}||9|read'
  'element|${ref[0]}||10|read'
  'element|${ref[key]}||0|read'
  'element|${ref[key]}||1|read'
  'element|${ref[key]}||2|read'
  'element|${ref[key]}||3|read'
  'element|${ref[key]}||4|read'
  'element|${ref[key]}||5|read'
  'element|${ref[key]}||6|read'
  'element|${ref[key]}||7|read'
  'element|${ref[key]}||8|read'
  'element|${ref[key]}||9|read'
  'element|${ref[key]}||10|read'
  'element|${#ref[@]}||0|read'
  'element|${#ref[@]}||1|read'
  'element|${#ref[@]}||2|read'
  'element|${#ref[@]}||3|read'
  'element|${#ref[@]}||4|read'
  'element|${#ref[@]}||5|read'
  'element|${#ref[@]}||6|read'
  'element|${#ref[@]}||7|read'
  'element|${#ref[@]}||8|read'
  'element|${#ref[@]}||9|read'
  'element|${#ref[@]}||10|read'
  'element|${!ref[@]}||2|read'
  'element|${!ref[@]}||5|read'
  'element|${!ref[@]}||6|read'
  'element|${!ref[@]}||7|read'
  'element|${ref[@]@Q}||0|read'
  'element|${ref[@]@Q}||1|read'
  'element|${ref[@]@Q}||2|read'
  'element|${ref[@]@Q}||3|read'
  'element|${ref[@]@Q}||4|read'
  'element|${ref[@]@Q}||5|read'
  'element|${ref[@]@Q}||6|read'
  'element|${ref[@]@Q}||7|read'
  'element|${ref[@]@Q}||8|read'
  'element|${ref[@]@Q}||9|read'
  'element|${ref[@]@Q}||10|read'
  'element|${ref@a}||0|read'
  'element|${ref@a}||1|read'
  'element|${ref@a}||2|read'
  'element|${ref@a}||3|read'
  'element|${ref@a}||4|read'
  'element|${ref@a}||6|read'
  'element|${ref@a}||7|read'
  'element|${ref@a}||8|read'
  'element|${ref@a}||9|read'
  'element|${ref@a}||10|read'
  'array|${ref[key]}||0|read'
  'array|${ref[key]}||1|read'
  'array|${ref[key]}||2|read'
  'array|${ref[key]}||3|read'
  'array|${ref[key]}||4|read'
  'array|${ref[key]}||5|read'
  'array|${ref[key]}||6|read'
  'array|${ref[key]}||7|read'
  'array|${ref[key]}||8|read'
  'array|${ref[key]}||9|read'
  'array|${ref[key]}||10|read'
  'array|$((ref + 1))||0|read'
  'array|$((ref + 1))||1|read'
  'array|$((ref + 1))||2|read'
  'array|$((ref + 1))||3|read'
  'array|$((ref + 1))||4|read'
  'array|$((ref + 1))||5|read'
  'array|$((ref + 1))||6|read'
  'array|$((ref + 1))||7|read'
  'array|$((ref + 1))||8|read'
  'array|$((ref + 1))||9|read'
  'array|$((ref + 1))||10|read'
  'sparse|$ref||0|read'
  'sparse|$ref||1|read'
  'sparse|$ref||2|read'
  'sparse|$ref||3|read'
  'sparse|$ref||4|read'
  'sparse|$ref||5|read'
  'sparse|$ref||6|read'
  'sparse|$ref||7|read'
  'sparse|$ref||8|read'
  'sparse|$ref||9|read'
  'sparse|$ref||10|read'
  'sparse|${ref}||0|read'
  'sparse|${ref}||1|read'
  'sparse|${ref}||2|read'
  'sparse|${ref}||3|read'
  'sparse|${ref}||4|read'
  'sparse|${ref}||5|read'
  'sparse|${ref}||6|read'
  'sparse|${ref}||7|read'
  'sparse|${ref}||8|read'
  'sparse|${ref}||9|read'
  'sparse|${ref}||10|read'
  'sparse|${ref[@]}||2|read'
  'sparse|${ref[@]}||6|read'
  'sparse|${ref[@]}||7|read'
  'sparse|${ref[*]}||2|read'
  'sparse|${ref[*]}||6|read'
  'sparse|${ref[*]}||7|read'
  'sparse|${ref[key]}||0|read'
  'sparse|${ref[key]}||1|read'
  'sparse|${ref[key]}||2|read'
  'sparse|${ref[key]}||3|read'
  'sparse|${ref[key]}||4|read'
  'sparse|${ref[key]}||5|read'
  'sparse|${ref[key]}||6|read'
  'sparse|${ref[key]}||7|read'
  'sparse|${ref[key]}||8|read'
  'sparse|${ref[key]}||9|read'
  'sparse|${ref[key]}||10|read'
  'sparse|${#ref}||0|read'
  'sparse|${#ref}||1|read'
  'sparse|${#ref}||2|read'
  'sparse|${#ref}||3|read'
  'sparse|${#ref}||4|read'
  'sparse|${#ref}||5|read'
  'sparse|${#ref}||6|read'
  'sparse|${#ref}||7|read'
  'sparse|${#ref}||8|read'
  'sparse|${#ref}||9|read'
  'sparse|${#ref}||10|read'
  'sparse|${ref@a}||0|read'
  'sparse|${ref@a}||1|read'
  'sparse|${ref@a}||2|read'
  'sparse|${ref@a}||3|read'
  'sparse|${ref@a}||4|read'
  'sparse|${ref@a}||6|read'
  'sparse|${ref@a}||7|read'
  'sparse|${ref@a}||8|read'
  'sparse|${ref@a}||9|read'
  'sparse|${ref@a}||10|read'
  'sparse|$((ref + 1))||0|read'
  'sparse|$((ref + 1))||1|read'
  'sparse|$((ref + 1))||2|read'
  'sparse|$((ref + 1))||3|read'
  'sparse|$((ref + 1))||4|read'
  'sparse|$((ref + 1))||5|read'
  'sparse|$((ref + 1))||6|read'
  'sparse|$((ref + 1))||7|read'
  'sparse|$((ref + 1))||8|read'
  'sparse|$((ref + 1))||9|read'
  'sparse|$((ref + 1))||10|read'
  'assoc|$ref||0|read'
  'assoc|$ref||1|read'
  'assoc|$ref||2|read'
  'assoc|$ref||3|read'
  'assoc|$ref||4|read'
  'assoc|$ref||5|read'
  'assoc|$ref||6|read'
  'assoc|$ref||7|read'
  'assoc|$ref||8|read'
  'assoc|$ref||9|read'
  'assoc|$ref||10|read'
  'assoc|${ref}||0|read'
  'assoc|${ref}||1|read'
  'assoc|${ref}||2|read'
  'assoc|${ref}||3|read'
  'assoc|${ref}||4|read'
  'assoc|${ref}||5|read'
  'assoc|${ref}||6|read'
  'assoc|${ref}||7|read'
  'assoc|${ref}||8|read'
  'assoc|${ref}||9|read'
  'assoc|${ref}||10|read'
  'assoc|${ref[@]}||0|read'
  'assoc|${ref[@]}||1|read'
  'assoc|${ref[@]}||2|read'
  'assoc|${ref[@]}||3|read'
  'assoc|${ref[@]}||4|read'
  'assoc|${ref[@]}||6|read'
  'assoc|${ref[@]}||7|read'
  'assoc|${ref[@]}||8|read'
  'assoc|${ref[@]}||9|read'
  'assoc|${ref[@]}||10|read'
  'assoc|${ref[*]}||0|read'
  'assoc|${ref[*]}||1|read'
  'assoc|${ref[*]}||2|read'
  'assoc|${ref[*]}||3|read'
  'assoc|${ref[*]}||4|read'
  'assoc|${ref[*]}||6|read'
  'assoc|${ref[*]}||7|read'
  'assoc|${ref[*]}||8|read'
  'assoc|${ref[*]}||9|read'
  'assoc|${ref[*]}||10|read'
  'assoc|${ref[key]}||0|read'
  'assoc|${ref[key]}||1|read'
  'assoc|${ref[key]}||2|read'
  'assoc|${ref[key]}||3|read'
  'assoc|${ref[key]}||4|read'
  'assoc|${ref[key]}||5|read'
  'assoc|${ref[key]}||6|read'
  'assoc|${ref[key]}||7|read'
  'assoc|${ref[key]}||8|read'
  'assoc|${ref[key]}||9|read'
  'assoc|${ref[key]}||10|read'
  'assoc|${#ref}||0|read'
  'assoc|${#ref}||1|read'
  'assoc|${#ref}||2|read'
  'assoc|${#ref}||3|read'
  'assoc|${#ref}||4|read'
  'assoc|${#ref}||5|read'
  'assoc|${#ref}||6|read'
  'assoc|${#ref}||7|read'
  'assoc|${#ref}||8|read'
  'assoc|${#ref}||9|read'
  'assoc|${#ref}||10|read'
  'assoc|${#ref[@]}||0|read'
  'assoc|${#ref[@]}||1|read'
  'assoc|${#ref[@]}||2|read'
  'assoc|${#ref[@]}||3|read'
  'assoc|${#ref[@]}||4|read'
  'assoc|${#ref[@]}||7|read'
  'assoc|${#ref[@]}||8|read'
  'assoc|${#ref[@]}||9|read'
  'assoc|${#ref[@]}||10|read'
  'assoc|${!ref[@]}||0|read'
  'assoc|${!ref[@]}||1|read'
  'assoc|${!ref[@]}||2|read'
  'assoc|${!ref[@]}||3|read'
  'assoc|${!ref[@]}||4|read'
  'assoc|${!ref[@]}||6|read'
  'assoc|${!ref[@]}||7|read'
  'assoc|${!ref[@]}||8|read'
  'assoc|${!ref[@]}||9|read'
  'assoc|${!ref[@]}||10|read'
  'assoc|${ref[@]@Q}||0|read'
  'assoc|${ref[@]@Q}||1|read'
  'assoc|${ref[@]@Q}||2|read'
  'assoc|${ref[@]@Q}||3|read'
  'assoc|${ref[@]@Q}||4|read'
  'assoc|${ref[@]@Q}||6|read'
  'assoc|${ref[@]@Q}||7|read'
  'assoc|${ref[@]@Q}||8|read'
  'assoc|${ref[@]@Q}||9|read'
  'assoc|${ref[@]@Q}||10|read'
  'assoc|${ref@a}||0|read'
  'assoc|${ref@a}||1|read'
  'assoc|${ref@a}||2|read'
  'assoc|${ref@a}||3|read'
  'assoc|${ref@a}||4|read'
  'assoc|${ref@a}||6|read'
  'assoc|${ref@a}||7|read'
  'assoc|${ref@a}||8|read'
  'assoc|${ref@a}||9|read'
  'assoc|${ref@a}||10|read'
  'assoc|$((ref + 1))||0|read'
  'assoc|$((ref + 1))||1|read'
  'assoc|$((ref + 1))||2|read'
  'assoc|$((ref + 1))||3|read'
  'assoc|$((ref + 1))||4|read'
  'assoc|$((ref + 1))||5|read'
  'assoc|$((ref + 1))||6|read'
  'assoc|$((ref + 1))||7|read'
  'assoc|$((ref + 1))||8|read'
  'assoc|$((ref + 1))||9|read'
  'assoc|$((ref + 1))||10|read'
  'chain|${ref[key]}||0|read'
  'chain|${ref[key]}||1|read'
  'chain|${ref[key]}||2|read'
  'chain|${ref[key]}||3|read'
  'chain|${ref[key]}||4|read'
  'chain|${ref[key]}||5|read'
  'chain|${ref[key]}||6|read'
  'chain|${ref[key]}||7|read'
  'chain|${ref[key]}||8|read'
  'chain|${ref[key]}||9|read'
  'chain|${ref[key]}||10|read'
  'chain|$((ref + 1))||0|read'
  'chain|$((ref + 1))||1|read'
  'chain|$((ref + 1))||2|read'
  'chain|$((ref + 1))||3|read'
  'chain|$((ref + 1))||4|read'
  'chain|$((ref + 1))||5|read'
  'chain|$((ref + 1))||6|read'
  'chain|$((ref + 1))||7|read'
  'chain|$((ref + 1))||8|read'
  'chain|$((ref + 1))||9|read'
  'chain|$((ref + 1))||10|read'
  'integer|${ref[key]}||0|read'
  'integer|${ref[key]}||1|read'
  'integer|${ref[key]}||2|read'
  'integer|${ref[key]}||3|read'
  'integer|${ref[key]}||4|read'
  'integer|${ref[key]}||5|read'
  'integer|${ref[key]}||6|read'
  'integer|${ref[key]}||7|read'
  'integer|${ref[key]}||8|read'
  'integer|${ref[key]}||9|read'
  'integer|${ref[key]}||10|read'
  'scalar|ref+=(z)||0|write'
  'scalar|ref+=(z)||1|write'
  'scalar|ref+=(z)||2|write'
  'scalar|ref+=(z)||3|write'
  'scalar|unset "ref[1]"||0|write'
  'scalar|unset "ref[1]"||1|write'
  'scalar|unset "ref[1]"||2|write'
  'scalar|unset "ref[1]"||3|write'
  'unset_target|((ref++))||0|write'
  'unset_target|((ref++))||1|write'
  'unset_target|((ref++))||2|write'
  'unset_target|((ref++))||3|write'
  'unset_target|let ref+=3||0|write'
  'unset_target|let ref+=3||1|write'
  'unset_target|let ref+=3||2|write'
  'unset_target|let ref+=3||3|write'
  'empty_target|ref+=(z)||0|write'
  'empty_target|ref+=(z)||1|write'
  'empty_target|ref+=(z)||2|write'
  'empty_target|ref+=(z)||3|write'
  'empty_target|unset "ref[1]"||0|write'
  'empty_target|unset "ref[1]"||1|write'
  'empty_target|unset "ref[1]"||2|write'
  'empty_target|unset "ref[1]"||3|write'
  'element|ref=(x y)||0|write'
  'element|ref=(x y)||1|write'
  'element|ref=(x y)||2|write'
  'element|ref=(x y)||3|write'
  'element|ref+=(z)||0|write'
  'element|ref+=(z)||1|write'
  'element|ref+=(z)||2|write'
  'element|ref+=(z)||3|write'
  'element|ref[1]=elem||0|write'
  'element|ref[1]=elem||1|write'
  'element|ref[1]=elem||2|write'
  'element|ref[1]=elem||3|write'
  'element|ref[2]=k||0|write'
  'element|ref[2]=k||1|write'
  'element|ref[2]=k||2|write'
  'element|ref[2]=k||3|write'
  'element|read -ra ref <<< "r1 r2"||0|write'
  'element|read -ra ref <<< "r1 r2"||1|write'
  'element|read -ra ref <<< "r1 r2"||2|write'
  'element|read -ra ref <<< "r1 r2"||3|write'
  'element|mapfile -t ref <<< $'\''m1\nm2'\''||0|write'
  'element|mapfile -t ref <<< $'\''m1\nm2'\''||1|write'
  'element|mapfile -t ref <<< $'\''m1\nm2'\''||3|write'
  'element|export ref=exported||0|write'
  'element|export ref=exported||1|write'
  'element|export ref=exported||2|write'
  'element|export ref=exported||3|write'
  'element|f() { local -n lr=target; lr=via_name; }; f||0|write'
  'element|f() { local -n lr=target; lr=via_name; }; f||1|write'
  'element|f() { local -n lr=target; lr=via_name; }; f||2|write'
  'element|f() { local -n lr=target; lr=via_name; }; f||3|write'
  'array|ref=new||0|write'
  'array|ref=new||1|write'
  'array|ref=new||2|write'
  'array|ref=new||3|write'
  'array|ref+=more||0|write'
  'array|ref+=more||1|write'
  'array|ref+=more||2|write'
  'array|ref+=more||3|write'
  'array|((ref = 4 * 2))||0|write'
  'array|((ref = 4 * 2))||1|write'
  'array|((ref = 4 * 2))||2|write'
  'array|((ref = 4 * 2))||3|write'
  'array|((ref++))||0|write'
  'array|((ref++))||1|write'
  'array|((ref++))||2|write'
  'array|((ref++))||3|write'
  'array|let ref+=3||0|write'
  'array|let ref+=3||1|write'
  'array|let ref+=3||2|write'
  'array|let ref+=3||3|write'
  'array|read -r ref <<< rd||0|write'
  'array|read -r ref <<< rd||1|write'
  'array|read -r ref <<< rd||2|write'
  'array|read -r ref <<< rd||3|write'
  'array|printf -v ref %s pv||0|write'
  'array|printf -v ref %s pv||1|write'
  'array|printf -v ref %s pv||2|write'
  'array|printf -v ref %s pv||3|write'
  'array|export ref=exported||0|write'
  'array|export ref=exported||1|write'
  'array|export ref=exported||2|write'
  'array|export ref=exported||3|write'
  'array|OPTIND=1; getopts ab ref -b||0|write'
  'array|OPTIND=1; getopts ab ref -b||1|write'
  'array|OPTIND=1; getopts ab ref -b||2|write'
  'array|OPTIND=1; getopts ab ref -b||3|write'
  'array|f() { local -n lr=ref; lr=via_local; }; f||0|write'
  'array|f() { local -n lr=ref; lr=via_local; }; f||1|write'
  'array|f() { local -n lr=ref; lr=via_local; }; f||2|write'
  'array|f() { local -n lr=ref; lr=via_local; }; f||3|write'
  'array|f() { local -n lr=target; lr=via_name; }; f||0|write'
  'array|f() { local -n lr=target; lr=via_name; }; f||1|write'
  'array|f() { local -n lr=target; lr=via_name; }; f||2|write'
  'array|f() { local -n lr=target; lr=via_name; }; f||3|write'
  'assoc|ref=new||0|write'
  'assoc|ref=new||1|write'
  'assoc|ref=new||2|write'
  'assoc|ref=new||3|write'
  'assoc|ref+=more||0|write'
  'assoc|ref+=more||1|write'
  'assoc|ref+=more||2|write'
  'assoc|ref+=more||3|write'
  'assoc|ref=(x y)||0|write'
  'assoc|ref=(x y)||1|write'
  'assoc|ref=(x y)||2|write'
  'assoc|ref=(x y)||3|write'
  'assoc|ref+=(z)||0|write'
  'assoc|ref+=(z)||1|write'
  'assoc|ref+=(z)||2|write'
  'assoc|ref+=(z)||3|write'
  'assoc|ref[1]=elem||0|write'
  'assoc|ref[1]=elem||1|write'
  'assoc|ref[1]=elem||2|write'
  'assoc|ref[1]=elem||3|write'
  'assoc|ref[2]=k||0|write'
  'assoc|ref[2]=k||1|write'
  'assoc|ref[2]=k||2|write'
  'assoc|ref[2]=k||3|write'
  'assoc|((ref = 4 * 2))||0|write'
  'assoc|((ref = 4 * 2))||1|write'
  'assoc|((ref = 4 * 2))||2|write'
  'assoc|((ref = 4 * 2))||3|write'
  'assoc|((ref++))||0|write'
  'assoc|((ref++))||1|write'
  'assoc|((ref++))||2|write'
  'assoc|((ref++))||3|write'
  'assoc|let ref+=3||0|write'
  'assoc|let ref+=3||1|write'
  'assoc|let ref+=3||2|write'
  'assoc|let ref+=3||3|write'
  'assoc|read -r ref <<< rd||0|write'
  'assoc|read -r ref <<< rd||1|write'
  'assoc|read -r ref <<< rd||2|write'
  'assoc|read -r ref <<< rd||3|write'
  'assoc|read -ra ref <<< "r1 r2"||0|write'
  'assoc|read -ra ref <<< "r1 r2"||1|write'
  'assoc|read -ra ref <<< "r1 r2"||2|write'
  'assoc|read -ra ref <<< "r1 r2"||3|write'
  'assoc|printf -v ref %s pv||0|write'
  'assoc|printf -v ref %s pv||1|write'
  'assoc|printf -v ref %s pv||2|write'
  'assoc|printf -v ref %s pv||3|write'
  'assoc|mapfile -t ref <<< $'\''m1\nm2'\''||0|write'
  'assoc|mapfile -t ref <<< $'\''m1\nm2'\''||1|write'
  'assoc|mapfile -t ref <<< $'\''m1\nm2'\''||3|write'
  'assoc|: ${ref:=assigned}||0|write'
  'assoc|: ${ref:=assigned}||1|write'
  'assoc|: ${ref:=assigned}||2|write'
  'assoc|: ${ref:=assigned}||3|write'
  'assoc|declare ref=declared||0|write'
  'assoc|declare ref=declared||1|write'
  'assoc|declare ref=declared||2|write'
  'assoc|declare ref=declared||3|write'
  'assoc|export ref=exported||0|write'
  'assoc|export ref=exported||1|write'
  'assoc|export ref=exported||2|write'
  'assoc|export ref=exported||3|write'
  'assoc|for ref in l1 l2; do :; done||0|write'
  'assoc|for ref in l1 l2; do :; done||1|write'
  'assoc|for ref in l1 l2; do :; done||2|write'
  'assoc|for ref in l1 l2; do :; done||3|write'
  'assoc|unset "ref[1]"||0|write'
  'assoc|unset "ref[1]"||1|write'
  'assoc|unset "ref[1]"||2|write'
  'assoc|unset "ref[1]"||3|write'
  'assoc|OPTIND=1; getopts ab ref -b||0|write'
  'assoc|OPTIND=1; getopts ab ref -b||1|write'
  'assoc|OPTIND=1; getopts ab ref -b||2|write'
  'assoc|OPTIND=1; getopts ab ref -b||3|write'
  'assoc|f() { local -n lr=ref; lr=via_local; }; f||0|write'
  'assoc|f() { local -n lr=ref; lr=via_local; }; f||1|write'
  'assoc|f() { local -n lr=ref; lr=via_local; }; f||2|write'
  'assoc|f() { local -n lr=ref; lr=via_local; }; f||3|write'
  'assoc|f() { local -n lr=target; lr=via_name; }; f||0|write'
  'assoc|f() { local -n lr=target; lr=via_name; }; f||1|write'
  'assoc|f() { local -n lr=target; lr=via_name; }; f||2|write'
  'assoc|f() { local -n lr=target; lr=via_name; }; f||3|write'
  'chain|ref+=(z)||0|write'
  'chain|ref+=(z)||1|write'
  'chain|ref+=(z)||2|write'
  'chain|ref+=(z)||3|write'
  'chain|((ref++))||0|write'
  'chain|((ref++))||1|write'
  'chain|((ref++))||2|write'
  'chain|((ref++))||3|write'
  'chain|let ref+=3||0|write'
  'chain|let ref+=3||1|write'
  'chain|let ref+=3||2|write'
  'chain|let ref+=3||3|write'
  'chain|unset "ref[1]"||0|write'
  'chain|unset "ref[1]"||1|write'
  'chain|unset "ref[1]"||2|write'
  'chain|unset "ref[1]"||3|write'
  'integer|ref=new||0|write'
  'integer|ref=new||1|write'
  'integer|ref=new||2|write'
  'integer|ref=new||3|write'
  'integer|ref+=more||0|write'
  'integer|ref+=more||1|write'
  'integer|ref+=more||2|write'
  'integer|ref+=more||3|write'
  'integer|ref=(x y)||0|write'
  'integer|ref=(x y)||1|write'
  'integer|ref=(x y)||2|write'
  'integer|ref=(x y)||3|write'
  'integer|ref+=(z)||0|write'
  'integer|ref+=(z)||1|write'
  'integer|ref+=(z)||2|write'
  'integer|ref+=(z)||3|write'
  'integer|ref[1]=elem||0|write'
  'integer|ref[1]=elem||1|write'
  'integer|ref[1]=elem||2|write'
  'integer|ref[1]=elem||3|write'
  'integer|ref[2]=k||0|write'
  'integer|ref[2]=k||1|write'
  'integer|ref[2]=k||2|write'
  'integer|ref[2]=k||3|write'
  'integer|read -r ref <<< rd||0|write'
  'integer|read -r ref <<< rd||1|write'
  'integer|read -r ref <<< rd||2|write'
  'integer|read -r ref <<< rd||3|write'
  'integer|read -ra ref <<< "r1 r2"||0|write'
  'integer|read -ra ref <<< "r1 r2"||1|write'
  'integer|read -ra ref <<< "r1 r2"||2|write'
  'integer|read -ra ref <<< "r1 r2"||3|write'
  'integer|printf -v ref %s pv||0|write'
  'integer|printf -v ref %s pv||1|write'
  'integer|printf -v ref %s pv||2|write'
  'integer|printf -v ref %s pv||3|write'
  'integer|mapfile -t ref <<< $'\''m1\nm2'\''||0|write'
  'integer|mapfile -t ref <<< $'\''m1\nm2'\''||1|write'
  'integer|mapfile -t ref <<< $'\''m1\nm2'\''||3|write'
  'integer|export ref=exported||0|write'
  'integer|export ref=exported||1|write'
  'integer|export ref=exported||2|write'
  'integer|export ref=exported||3|write'
  'integer|unset "ref[1]"||0|write'
  'integer|unset "ref[1]"||1|write'
  'integer|unset "ref[1]"||2|write'
  'integer|unset "ref[1]"||3|write'
  'integer|OPTIND=1; getopts ab ref -b||0|write'
  'integer|OPTIND=1; getopts ab ref -b||1|write'
  'integer|OPTIND=1; getopts ab ref -b||2|write'
  'integer|OPTIND=1; getopts ab ref -b||3|write'
  'integer|f() { local -n lr=ref; lr=via_local; }; f||0|write'
  'integer|f() { local -n lr=ref; lr=via_local; }; f||1|write'
  'integer|f() { local -n lr=ref; lr=via_local; }; f||2|write'
  'integer|f() { local -n lr=ref; lr=via_local; }; f||3|write'
  'integer|f() { local -n lr=target; lr=via_name; }; f||0|write'
  'integer|f() { local -n lr=target; lr=via_name; }; f||1|write'
  'integer|f() { local -n lr=target; lr=via_name; }; f||2|write'
  'integer|f() { local -n lr=target; lr=via_name; }; f||3|write'
)
[ -n "${list_only-}" ] && return 0
is_pending_run=1
. "${BASH_SOURCE%/*}/nameref_contexts_matrix.bash"
